spring:
  datasource:
    url: jdbc:mysql://localhost:3306/papertrail?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: localhost
    port: 25
    username: dev
    password: dev
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

app:
  security:
    jwt:
      secret-key: budqd3g39zOpV0aEvBqxlTiRm4HvDHKWlkajfdkeirekklakjhdsfs5f454fsdaf54654a54fsd54f5ds4f5
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      picture-output-path: ./uploads