services:
  # Database server
  database:
    container_name: mysql-papertrail
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: papertrail
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    volumes:
        - mysql-vol:/var/lib/mysql
    ports:
        - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - papertrail-network
    restart: unless-stopped

  # MailDev mail server  // todo user docker:maildev/maildev mail server if live mail server not set up
  mail-dev:
    container_name: mail-dev-papertrail
    image: maildev/maildev
    ports:
      - 1080:1080
      - 25:1025
    networks:
      - papertrail-network


  # Backend api
  papertrail-api:
    container_name: papertrail-api
    image: papertrail-api-prod:1.0.0
    ports:
      - 8080:8080
    networks:
      - papertrail-network
    depends_on:
      database:
        condition: service_healthy

  # Frontend ui
  papertrail-ui:
    container_name: papertrail-ui
    image: papertrail-ui-prod:1.0.0
    ports:
      - 4200:80
    networks:
      - papertrail-network
    depends_on:
      - papertrail-api

  # keycloak
  keycloak:
    container_name: keycloak-papertrail
    image: quay.io/keycloak/keycloak:25.0.1
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - papertrail-network
    command:
      - "start-dev"

volumes:
  mysql-vol:
    driver: local
#  keycloak:
#    driver: local

networks:
  papertrail-network:
    driver: bridge