services:
  # Database server
  database:
    container_name: mysql-papertrail
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: papertrail
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    volumes:
        - mysql-vol:/var/lib/mysql
    ports:
        - 3306:3306
    networks:
        - papertrail-network
    restart: unless-stopped

  # MailDev mail server
  mail-dev:
    container_name: mail-dev-papertrail
    image: maildev/maildev
    ports:
      - 1080:1080
      - 25:1025


volumes:
  mysql-vol:
    driver: local

networks:
  papertrail-network:
    driver: bridge